// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  ethereum,
  JSONValue,
  TypedMap,
  Entity,
  Bytes,
  Address,
  BigInt
} from "@graphprotocol/graph-ts";

export class MatchOrderResults extends ethereum.Event {
  get params(): MatchOrderResults__Params {
    return new MatchOrderResults__Params(this);
  }
}

export class MatchOrderResults__Params {
  _event: MatchOrderResults;

  constructor(event: MatchOrderResults) {
    this._event = event;
  }

  get orderHashes(): Array<Bytes> {
    return this._event.parameters[0].value.toBytesArray();
  }

  get results(): Array<boolean> {
    return this._event.parameters[1].value.toBooleanArray();
  }
}

export class TradeV2 extends ethereum.SmartContract {
  static bind(address: Address): TradeV2 {
    return new TradeV2("TradeV2", address);
  }
}
